### ISSUE TITLE
Turistas no pueden solicitar la ciudadania

### ISSUE THREAD

**Issue by Shrewd** [JavierGonzalez/POL#240]
Fatal error: Uncaught TypeError: mysqli_fetch_assoc(): Argument #1 ($result) must be of type mysqli_result, bool given in /var/www/vhosts/virtualpol.com/pol.virtualpol.com/+/functions.php:18 Stack trace: #0 /var/www/vhosts/virtualpol.com/pol.virtualpol.com/+/functions.php(18): mysqli_fetch_assoc() #1 /var/www/vhosts/virtualpol.com/pol.virtualpol.com/registrar/solicitar-ciudadania.php(8): r() #2 /var/www/vhosts/virtualpol.com/pol.virtualpol.com/$maxsim.php(31): include_once('...') #3 {main} thrown in /var/www/vhosts/virtualpol.com/pol.virtualpol.com/+/functions.php on line 18

**Comment by Logatto** [comment]
@Shrewd no lo logro replicar, podemos saber si aun sucede?
